REGION_DATE_FORMAT_DICT = {
    "Hyderabad": "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
    "Chennai": "%H:%M:%S UTC / %d %b %Y\n\x0c",
    "Vishakapatnam": "%H:%M / %d-%b-%Y\n\x0c",
    "Kochi": "Date:%d/%m/%Y\nTime:%H:%M:%S UTC\n\n  \n\x0c",
    "Thiruvananthapuram": "%Y/%m/%d %H:%M:%S\n\x0c",
    "Goa": "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
    "Sriharikota": "%H:%M:%S UTC / %d %b %Y\n\x0c",
    "Machilipatnam": "%H:%M / %d-%b-%Y\n\x0c",
    "Karaikal": "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
    "Solapur": "%H:%M / %d-%b-%Y\n\x0c",
    "Bhopal": "%H:%M:%S2\n%d %b 20°%y UTC\n\x0c",
    "Paradip": "%H:%M:%Sz\n%d %b 20°%y UTC\n\x0c",
    "Kolkata": "%H:%M / %d-%b-%Y\n\x0c",
    "Agartala": "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
    "Sohra": "%Y/%m/%d %H:%M:%S (UTC)\n\x0c",
    "Mohanbari": "%H:%M:%S2\n%d %b %Y UTC\n\x0c",
    "Patna": "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
    "Lucknow": "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
    "Bhuj": "%Y/%m/%d %H:%M:%S (UTC)\n\x0c",
    "Jaipur": "%H:%M:%S2\n\n%d %b %Y ut!\n\x0c",
    "Delhi": "%H:%M:%S UTC / %d-%b-%Y\n\x0c",
    "Mukteshwar": "%H:%M:%S UTC / %d-%b-%Y\n\x0c",
    "Lansdowne": "%H:%M:%S UTC / %d-%b-%Y\n\x0c",
    "Patiala": "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
    "Surkandaji": "%H:%M:%S UTC / %d-%b-%Y\n\x0c",
    "Kufri": "%H:%M:%S UTC / %d-%b-%Y\n\x0c",
    "Murari": "%H:%M:%S UTC / %d-%b-%Y\n\x0c",
    "Jot": "%H:%M:%S UTC / %d-%b-%Y\n\x0c",
    "Jammu": "%H:%M:%S UTC / %d-%b-%Y\n\x0c",
    "Srinagar": "%H:%M:%S\n%d/%b/%Y UTC\n\x0c",
    "Nagpur": "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
    "Banihal": "%H:%M:%S UTC / %d-%b-%Y\n\x0c",
    "Mumbai": "%H:%M:%S UTC / %d %b %Y\n\x0c",
    "Gopalpur": "%Y/%m/%d %H:%M:%S (UTC)\n\x0c",
}

REGION_NAME_POSSIBLE_DATE_FORMATS = {
    "Hyderabad": ["%H:%M:%S2\n%d %b %Y UTC\n\x0c", "%H:%M:%Sz2\n%d %b %Y UTC\n\x0c"],
    "Goa": [
        "%H:%M:%S2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n4%d %b %Y UTC\n\x0c",
        "%H:%M:%S2\n4%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz\n4%d %b %Y UTC\n\x0c",
    ],
    "Bhopal": [
        "%H:%M:%Sz\n%d %b 20°%y UTC\n\x0c",
        "%H:%M:%S2\n4%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n4%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz\n4%d %b %Y UTC\n\x0c",
        "%H:%M:%S2\nbo %b 20°%y UTC\n\x0c",
        "%H:%M:%S2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n%d %b %Y UTC\n\x0c",
    ],
    "Agartala": [
        "%H:%M:%S2\n%d %b %Y UTC\n\x0c",
        " \n\n%H:%M:%S2\n%d %b %Y UTC\n\x0c",
        " \n\n%H:%M:%Sz2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n%d %b %Y UTC\n\x0c",
        " \n\n%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
        "%H:%M:%S2z\n%d %b %Y UTC\n\x0c",
    ],
    "Lucknow": [
        "%H:%M:%Sz2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n4%d %b %Y UTC\n\x0c",
        "%H:%M:%S2\n4%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz\n4%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n%dg %b %Y UTC\n\x0c",
        "%H:%M:%S2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz\n\\%d %b %Y UTC\n\x0c",
        "%H:%M:%S2\n\\%d %b %Y UTC\n\x0c",
    ],
    "Patna": ["%H:%M:%S2\n%d %b %Y UTC\n\x0c", " \n\n%H:%M:%Sz\n%d %b %Y UTC\n\x0c"],
    "Srinagar": ["%H:%M:%S\n%d/d%b/%Y UTC\n\x0c"],
    "Patiala": [
        "%H:%M:%S2\n%d %b %Y UTC\n\x0c",
        " \n\n%H:%M:%S2\n%d %b %Y UTC\n\x0c",
        " \n\n%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n%d %b %Y UTC\n\x0c",
    ],
    "Paradip": [
        "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
        "%H:%M:%S2\n5%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%S2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%S2\n%d %b 20°%y UTC\n\x0c",
    ],
    "Karaikal": [
        "%H:%M:%S2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n%d %b %Y UTC\n\x0c",
        "%H:%M: %Sz\n%d %b %Y UTC\n\x0c",
    ],
    "Jaipur": [
        "%H:%M:%S2\n\n%d %b %Y uti\n\x0c",
        "%H:%M:%S2\n\n%d %b %Y ut\n\x0c",
        "%H:%M:%S7\n\n%d %b %Y ut!\n\x0c",
        "%H:%M:%S7\n\n%d %b %Y ut\n\x0c",
    ],
    "Mohanbari": [
        "%H:%M:%Sz2\n%d %b %Y UTC\n\x0c",
        " \n\n%H:%M:%Sz2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
        " \n\n%H:%M:%S2\n%d %b %Y UTC\n\x0c",
        " \n\n%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
    ],
    "Nagpur": [" \n\n%H:%M:%Sz\n%d %b %Y UTC\n\x0c"],
    "Delhi": [
        "%H:%M:%S UTC / %d-%b-%Y\n\x0c",
        "%H:%M:%Sz\n%d %b %Y UTC\n\x0c",
        "%H:%M:%S2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz2\n4%d %b %Y UTC\n\x0c",
        "%H:%M:%Sz\n4%d %b %Y UTC\n\x0c",
        "%H:%M:%S2\n4%d %b %Y UTC\n\x0c",
    ],
    "Chennai": ["%H:%M / %d-%b-%Y\n\x0c"],
    "Sriharikota": ["%H:%M:%S UTC / o%d %b %Y\n\x0c"],
    "Gopalpur": ["%Y/%m/%d %H:%M:%S (UTC) ‘|~*", "%Y/%m/%d %H:%M:%S"],
    "Mumbai": ["%Y-%m-%d_%H:%M:%S_UTC\n\x0c"],
    "Mukteshwar": ["%H:%M:%S UTC | %d-%b-%Y\n\x0c"],
}

